# General config
spring.profiles.active=local
# Yusuf config
api.version=v1
api.base-url=/api/${api.version}
api.base.auth.login=/auth/login
api.base.auth.logout=/auth/logout
api.base.auth.user=/auth/user
app.base-url=${ecodigit.http}://${ecodigit.hostname}:4200${api.base-url}
app.base.extern=/extern/**
app.base.extern.secret=externSecret
ecodigit.notification.retention.period.in.days=30
server.servlet.context-path=${api.base-url}
spring.servlet.multipart.max-file-size=3000MB
spring.servlet.multipart.max-request-size=3000MB
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=true
server.servlet.session.cookie.same-site=strict
server.servlet.session.timeout=30m
## Frontend
frontend.base-url=${ecodigit.http}://${ecodigit.hostname}:4200
frontend.sessioncookie.name=JSESSIONID
## Swagger
swagger.ui.uri=/swagger-ui/**
## Api Docs
api.docs.uri=/v3/api-docs/**
# Keycloak
# OAuth2 Client Registration
spring.security.oauth2.client.registration.keycloak.client-id=yusuf-spring-client
spring.security.oauth2.client.registration.keycloak.client-secret=**********
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.redirect-uri=${ecodigit.http}://${ecodigit.hostname}:8080${api.base-url}/login/oauth2/code/keycloak
spring.security.oauth2.client.registration.keycloak.scope=openid,profile,email
spring.security.oauth2.client.registration.keycloak.client-name=yusuf

# OAuth2 Provider: Endpunkte explizit, kein issuer-uri
spring.security.oauth2.client.provider.keycloak.authorization-uri=${keycloak.external.url}/realms/ecodigit/protocol/openid-connect/auth
spring.security.oauth2.client.provider.keycloak.token-uri=${keycloak.internal.url}/realms/ecodigit/protocol/openid-connect/token
spring.security.oauth2.client.provider.keycloak.jwk-set-uri=${keycloak.internal.url}/realms/ecodigit/protocol/openid-connect/certs

# Custom Keycloak Variables
keycloak.realmName=ecodigit
keycloak.token-uri=/realms/${keycloak.realmName}/protocol/openid-connect/token
keycloak.logout-uri=/realms/${keycloak.realmName}/protocol/openid-connect/logout
keycloak.users-uri=/admin/realms/${keycloak.realmName}/users
keycloak.login-url=/auth/login
keycloak.authorization-redirect=${app.base-url}/oauth2/authorization/keycloak
keycloak.logout-url=/auth/logout
spring.flyway.locations=classpath:db/migration/postgres


