services:
  database:
    image: postgres:16-bookworm
    container_name: database
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./../dependencies/database/init-database.sql:/docker-entrypoint-initdb.d/init-database.sql
  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    container_name: keycloak
    environment:
      #     Database Configs
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://database:5432/keycloak
      KC_DB_USERNAME: ${DB_USER}
      KC_DB_PASSWORD: ${DB_PASSWORD}
      #     Host Configs
      KC_HOSTNAME: "http://localhost:8090"
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HOSTNAME_BACKCHANNEL_DYNAMIC: true
      #     Advanced Configs
      KC_LOG_LEVEL: info
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true
      #     Credentials
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      #     Security Configs
      KC_HTTP_ENABLED: true
      KC_PROXY: edge
      KC_CORS: true

      KC_CUSTOM_YUSUF_HOST: "http://localhost:8080/api/v1"
      KC_CUSTOM_COBB_HOST: "http://localhost:4200"
    command: "start-dev --import-realm"
    depends_on:
      - database
      - mailhog
    ports:
      - "8090:8080"
    volumes:
      - ./../dependencies/keycloak/realms/ecodigit-realm.json:/opt/keycloak/data/import/ecodigit-realm.json
      - ./../dependencies/keycloak/auth-theme:/opt/keycloak/themes/ecodigit
  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ':9001'
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio_data:/data
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    volumes:
      - mailhog_data:/mailhog/data
  timescale:
    image: timescale/timescaledb:latest-pg14
    container_name: timescale
    environment:
      POSTGRES_USER: ${TIMESCALE_USER}
      POSTGRES_PASSWORD: ${TIMESCALE_PASSWORD}
      POSTGRES_DB: timescale_database
    ports:
      - "5433:5432"
    volumes:
      - timescale_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  restore-dummy:
    image: restore-dummy
    build:
      context: ../dependencies/dummy
      dockerfile: Dockerfile
    environment:
      PG_HOST: database
      PG_PORT: 5432
      PG_USER: ${DB_USER}
      PG_PASSWORD: ${DB_PASSWORD}
      PG_DB: testbench_db
      PG_DUMP: example_data_postgres.dump

      TS_HOST: 10.1.104.105
      TS_PORT: 5433
      TS_USER: ${TIMESCALE_USER}
      TS_PASSWORD: ${TIMESCALE_PASSWORD}
      TS_DB: ${TIMESCALE_DB}
      TS_DUMP: example_data_timescale.dump

      MINIO_HOST: http://10.1.104.105:9000
      MINIO_USER: minioadmin
      MINIO_PASSWORD: minioadmin
      MINIO_BUCKET: applicationvariants
      MINIO_FOLDER: files_minio
    volumes:
      - ../dependencies/dummy:/data:ro
    profiles: ["restore"]

volumes:
  postgres_data:
  minio_data:
  mailhog_data:
  timescale_data:
  rabbitmq_data:
      
