services:
  proxy:
    image: dev-proxy:latest
    build: ../dependencies/dev-proxy
    depends_on:
      - keycloak
      - yusuf
      - cobb
    ports:
      - '80:80'

  cobb:
    build: ./../cobb
    container_name: cobb
    depends_on:
      - yusuf

  yusuf:
    build: ./../yusuf
    container_name: yusuf
    environment:
      SPRING_PROFILES_ACTIVE: "dev"
      ECODIGIT_HOSTNAME: ecodigit.localhost
    depends_on:
      - database
      - minio
      - keycloak
      - rabbitmq

  database:
    image: postgres:16-bookworm
    container_name: database
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./../dependencies/database/init-database.sql:/docker-entrypoint-initdb.d/init-database.sql

  keycloak:
    build: ./../dependencies/keycloak
    container_name: keycloak
    environment:
      # Database Configs
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://database:5432/keycloak
      KC_DB_USERNAME: ${DB_USER}
      KC_DB_PASSWORD: ${DB_PASSWORD}

      # Host Configs
      KC_HOSTNAME: "http://ecodigit.localhost/auth/"
      KC_HOSTNAME_BACKCHANNEL_DYNAMIC: true
      KC_HTTP_RELATIVE_PATH: "/auth/"

      # Advanced Configs
      KC_LOG_LEVEL: info
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true

      # Credentials
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      KC_CUSTOM_YUSUF_HOST: "http://ecodigit.localhost/api/v1"
      KC_CUSTOM_COBB_HOST: "http://ecodigit.localhost"

    depends_on:
      - database

  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ':9001'
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio_data:/data
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    volumes:
      - mailhog_data:/mailhog/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
volumes:
  postgres_data:
  minio_data:
  mailhog_data:
  rabbitmq_data:
